apiVersion: v1
kind: Service
metadata:
  name: docker-main-go-service
spec:
  selector:
    app: docker-main-go
  ports:
  - protocol: "TCP"
    port: 31000
    targetPort: 5500
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-main-go
spec:
  selector:
    matchLabels:
      app: docker-main-go
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-main-go
    spec:
      containers:
      - name: docker-main-go
        image: veena1127/docker-main-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5500
